//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtelRezervasyonDBEntities : DbContext
    {
        public OtelRezervasyonDBEntities()
            : base("name=OtelRezervasyonDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Konaklayan> Konaklayan { get; set; }
        public virtual DbSet<KonaklayanDetay> KonaklayanDetay { get; set; }
        public virtual DbSet<Oda> Oda { get; set; }
        public virtual DbSet<Rezervasyon> Rezervasyon { get; set; }
        public virtual DbSet<RezervasyonDetay> RezervasyonDetay { get; set; }
        public virtual DbSet<RezerveEden> RezerveEden { get; set; }
    }
}
