//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oda()
        {
            this.RezervasyonDetay = new HashSet<RezervasyonDetay>();
        }
    
        public int OdaID { get; set; }
        public string OdaNo { get; set; }
        public byte Kapasite { get; set; }
        public byte OdaTuruEnum { get; set; }
        public bool Silindi { get; set; }
        public decimal Fiyat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezervasyonDetay> RezervasyonDetay { get; set; }
    }
}
