//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervasyon()
        {
            this.RezervasyonDetay = new HashSet<RezervasyonDetay>();
        }
    
        public int RezervasyonID { get; set; }
        public Nullable<int> RezerveEdenID { get; set; }
        public Nullable<System.DateTime> GirisTarihi { get; set; }
        public Nullable<System.DateTime> CikisTarihi { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<bool> Odendi { get; set; }
        public Nullable<bool> Iptal { get; set; }
        public Nullable<bool> Silindi { get; set; }
    
        public virtual RezerveEden RezerveEden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezervasyonDetay> RezervasyonDetay { get; set; }
    }
}
